### PR TITLE
fixing datetime call in tools/zbfind

### PR DESCRIPTION
**Pull request by SrEdeu**

### CODE REVIEW

**Comment by rmspeers** [comment]
@SrEdeu upon merging this I looked and realized this appears to not work on Python 2.7 at least:
```
$ python -V
Python 2.7.10
$ python
Python 2.7.10 (default, Aug 17 2018, 19:45:58) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import datetime
>>> datetime.datetime.now()
datetime.datetime(2019, 3, 24, 11, 24, 56, 974321)
>>> datetime.now()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'now'
```

Which version are you on that you see issues with the way it was done? Can you send similar output as to the above?

**Comment by SrEdeu** [comment]
@rmspeers I'm also working on Python 2.7, and having same outputs as you. 
When I execute zbfind I get the following.
`sudo python zbfind -c 26
# DEBUG Clearing overflow
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "zbfind", line 1040, in run
    nowstr = str(datetime.datetime.now())
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
` 
I assumed that it was because datetime was imported as
`from datetime import datetime` 
but is not.. So I don't know why I'm getting this error, as date time.now() is working fine for me without any other modification.
